### ISSUE TITLE
double check if tutorial dialogue is skippable and make sure it isn't

### ISSUE THREAD

**Issue by BlizzardBunny** [BlizzardBunny/Digital-Footprints#31]
Tutorial skip is kinda wonky because of the way it has to be done in order, so let's just disable skip for the tutorial lang

**Comment by TheMagicalFishTaco** [comment]
I think we can instead make it skip the entire tutorial stage

**Comment by TheMagicalFishTaco** [comment]
More playtesting required, but so far so good
